# Generated by Django 5.1.4 on 2025-01-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addnewlab_dmppage_dmpsearchpage_dmpviewpage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddNewLab',
        ),
    ]
