# Generated by Django 5.1.4 on 2025-01-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_addnewlab'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elab_base_url', models.URLField(blank=True, verbose_name='elab url')),
                ('jenkins_base_url', models.URLField(blank=True, verbose_name='jenkins url')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
