# Generated by Django 5.1 on 2024-09-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addnewlab_dmppage_dmpsearchpage_dmpviewpage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addnewlab',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='addnewlab',
            name='thankyou_page_title',
        ),
    ]
