# Generated by Django 5.0.6 on 2024-06-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_navigationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
