# Generated by Django 5.1 on 2024-09-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_addnewlab_intro_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SRSubmissionPage',
            new_name='ServiceRequestSubmissionPage',
        ),
        migrations.RemoveField(
            model_name='dmpsearchpage',
            name='intro',
        ),
        migrations.DeleteModel(
            name='SRForSamplePage',
        ),
    ]
