# Generated by Django 5.0.6 on 2024-06-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_navigationsettings_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='github_icon',
            field=models.ImageField(blank=True, upload_to='icons'),
        ),
    ]
