# Generated by Django 5.1 on 2024-09-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_srsubmissionpage_servicerequestsubmissionpage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleEntryForm',
        ),
    ]
