# Generated by Django 5.0.6 on 2024-05-20 13:51

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_body'),
        ('wagtailcore', '0093_uploadedfile'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='a_link',
            field=models.ForeignKey(blank=True, help_text='Insert a link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='a link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='another_text',
            field=models.CharField(blank=True, help_text='Another Text!', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Homepage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='introduction_text',
            field=models.CharField(blank=True, help_text='Write an introduction to the site', max_length=255),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiche_text',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=255),
        ),
    ]
