# Generated by Django 5.0.6 on 2024-06-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_navigationsettings_github_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='twitter_url',
        ),
    ]
