# Generated by Django 5.0.6 on 2024-06-25 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_navigationsettings_twitter_url'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NavigationSettings',
            new_name='FooterSettings',
        ),
    ]
