# Generated by Django 5.0.6 on 2024-05-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_formfield_options_remove_formfield_choices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='CustomFormSubmission',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.DeleteModel(
            name='FormPage',
        ),
    ]
