# Generated by Django 5.0.6 on 2024-07-01 11:48

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_body_homepage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro',
            field=models.CharField(default='', max_length=250),
        ),
    ]
