# Generated by Django 5.1 on 2024-08-20 12:27

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_lamesamplespage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSampleForm',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('thankyou_page_title', models.CharField(help_text="Title text to use for the 'thank you' page", max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SRForSamplePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='lagesamplespage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='lamesamplespage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='samplespage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='DynamicFormRedirectPage',
        ),
        migrations.DeleteModel(
            name='LageSamplesPage',
        ),
        migrations.DeleteModel(
            name='LameSamplesPage',
        ),
        migrations.DeleteModel(
            name='SamplesPage',
        ),
    ]
