# Generated by Django 5.1 on 2024-08-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_dynamicformredirectpage_samplespage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralSampleForm',
            new_name='GeneralSamplePage',
        ),
    ]
