# Generated by Django 5.1 on 2024-08-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_generalsampleform_generalsamplepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplespage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='DynamicFormRedirectPage',
        ),
        migrations.DeleteModel(
            name='SamplesPage',
        ),
    ]
