# Generated by Django 5.0.6 on 2024-06-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customformdata_customformpage_formpage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='CustomFormSubmission',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.DeleteModel(
            name='FormPage',
        ),
    ]
