# Generated by Django 5.1 on 2024-08-28 13:43

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0002_administration_instruments_instrumentxtechnique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposals',
            name='proposal_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('c2bdfabe-dc50-46a3-be97-c7ddac2844d5'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('6b7273ff-8b8e-47cb-a443-369c848f97bb'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
