# Generated by Django 5.0.6 on 2024-07-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0002_laboratories'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLAMEModel',
            fields=[
                ('lameintro', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('datausername', models.CharField(blank=True, max_length=255)),
                ('lamefield', models.DateField()),
            ],
            options={
                'db_table': 'customlamemodel',
            },
        ),
    ]
