# Generated by Django 5.0.6 on 2024-07-15 13:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0002_administration_lagesample_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='uuid',
            field=models.CharField(default=uuid.UUID('acdda316-c1f7-4940-a2d6-7e7214bd5325'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customappmodel',
            name='datavarchar',
            field=models.CharField(default=uuid.UUID('ef4b5062-ffd4-4aa2-bc92-75cde3eaf6c0'), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='uuid',
            field=models.CharField(default=uuid.UUID('d0318188-edd3-4c6b-902a-1dcfa0203318'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
