# Generated by Django 5.1 on 2024-08-29 09:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0002_administration_instruments_instrumentxtechnique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('f57f9540-9ef0-416b-ad2f-2ebecb4a3434'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
