# Generated by Django 5.0.6 on 2024-07-08 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0002_laboratories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('orid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=128)),
                ('datausername', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'administration',
            },
        ),
        migrations.CreateModel(
            name='lageSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_description', models.CharField(max_length=500)),
                ('datausername', models.CharField(max_length=50)),
                ('orid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRP_CDM_app.administration')),
            ],
            options={
                'db_table': 'lagesample',
            },
        ),
        migrations.DeleteModel(
            name='Laboratories',
        ),
    ]
