# Generated by Django 5.1 on 2024-09-09 08:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0002_administration_instruments_instrumentxtechnique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('90e24c85-3a21-4364-9ec2-df5acde9a20c'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
