# Generated by Django 5.0.6 on 2024-07-16 14:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0003_alter_administration_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lagesample',
            name='file_in',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administration',
            name='dmptitle',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='administration',
            name='uuid',
            field=models.CharField(default=uuid.UUID('1a19f31f-016a-428c-bcc4-9a2f52afe773'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customappmodel',
            name='datavarchar',
            field=models.CharField(default=uuid.UUID('fbcabeb3-18dd-44a0-80d2-87eb43924456'), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='expected_date_of_delivery',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='uuid',
            field=models.CharField(default=uuid.UUID('84778e36-4e1a-4176-8b14-f02abd7b240e'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
