# Generated by Django 5.0.6 on 2024-07-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0003_administration_lagesample_delete_laboratories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lagesample',
            name='orid',
        ),
    ]
