# Generated by Django 5.1 on 2024-09-02 09:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0003_proposals_proposal_date_alter_administration_sr_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='short_affiliation',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('6ae72957-4bdd-404f-b29b-6f5b17e3722c'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('067146f7-71e5-4a94-a912-80067a7047e9'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
