# Generated by Django 5.1 on 2024-08-29 10:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0003_alter_administration_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('7f81d368-27de-4175-9b52-3c9043579667'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
