# Generated by Django 5.0.6 on 2024-07-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0004_remove_lagesample_orid'),
    ]

    operations = [
        migrations.CreateModel(
            name='lameSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_description', models.CharField(max_length=128)),
                ('device', models.CharField(max_length=50)),
                ('datausername', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'lamesample',
            },
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sample_description',
            field=models.TextField(max_length=500),
        ),
    ]
