# Generated by Django 5.1 on 2024-09-02 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0004_users_short_affiliation_alter_administration_sr_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('98f65755-3bf6-4d56-8eb5-8fe97c02c8ae'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('3c9ab7d6-595d-4e25-9dbc-582a2ec210df'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicerequests',
            name='sr_id',
            field=models.CharField(max_length=42, primary_key=True, serialize=False),
        ),
    ]
