# Generated by Django 5.0.6 on 2024-07-16 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0004_lagesample_file_in_alter_administration_dmptitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='uuid',
            field=models.CharField(default=uuid.UUID('f9340d0f-d55c-444f-82ae-357e9b87b1c3'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customappmodel',
            name='datavarchar',
            field=models.CharField(default=uuid.UUID('75699eeb-5126-4fb3-849c-3d793f9529a9'), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='file_in',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sample_back',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='uuid',
            field=models.CharField(default=uuid.UUID('58bd7875-feb8-419a-8c63-824af15a5077'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
