# Generated by Django 5.1 on 2024-08-29 11:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0004_alter_administration_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('5724f97e-e499-408a-8349-5c4092a58d43'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesamples',
            name='type',
            field=models.CharField(blank=True),
        ),
    ]
