# Generated by Django 5.1 on 2024-09-09 09:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0004_alter_administration_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('932d9fa4-cb1f-4ed2-b2fe-2e2d97651dbb'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
