# Generated by Django 5.1 on 2024-08-29 13:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0005_alter_administration_sr_id_alter_lagesamples_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='lab_id',
            field=models.ForeignKey(default='LAGE', on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.laboratories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('32a7c9e8-90cf-4d26-9b5c-87617d315d30'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
