# Generated by Django 5.1 on 2024-09-09 09:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0005_alter_administration_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('72b090f0-4735-4d58-b276-bc68957fd718'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
