# Generated by Django 5.0.6 on 2024-07-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0005_lamesample_alter_lagesample_sample_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ladeSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacenter', models.CharField(max_length=128)),
                ('gpu', models.CharField(max_length=50)),
                ('datausername', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ladesample',
            },
        ),
    ]
