# Generated by Django 5.1 on 2024-09-02 11:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0005_alter_administration_sr_id_alter_lagesample_sr_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('7d7080cd-c311-4dca-a2b2-3283f9383d7a'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('a3a6f119-656a-470a-9e3a-725fe40b5422'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='samples',
            name='sample_id',
            field=models.CharField(max_length=42, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicerequests',
            name='sr_id',
            field=models.CharField(max_length=37, primary_key=True, serialize=False),
        ),
    ]
