# Generated by Django 5.0.6 on 2024-07-17 11:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0006_remove_lagesample_file_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='labDMP',
            fields=[
                ('labname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('datausername', models.CharField(max_length=50)),
                ('datageneric', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'labdmp',
            },
        ),
        migrations.AlterField(
            model_name='administration',
            name='uuid',
            field=models.CharField(default=uuid.UUID('46d6b017-0bbd-441d-9d3c-70eb9133f381'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customappmodel',
            name='datavarchar',
            field=models.CharField(default=uuid.UUID('e2d92913-9632-4d2c-b93f-f66ef5c69f7a'), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='uuid',
            field=models.CharField(default=uuid.UUID('ec651724-8b8f-4e9e-8593-ec8970b835da'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
