# Generated by Django 5.1 on 2024-09-09 14:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0006_alter_administration_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('0011b932-8e45-4a3d-b11e-2ee0f28d0b73'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
