# Generated by Django 5.0.6 on 2024-07-10 08:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0006_ladesample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administration',
            name='orid',
        ),
        migrations.RemoveField(
            model_name='ladesample',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lagesample',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lamesample',
            name='id',
        ),
        migrations.AddField(
            model_name='administration',
            name='uuid',
            field=models.CharField(default=uuid.UUID('bb4e7c5f-1a33-480c-9360-f5235598a8c6'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='ladesample',
            name='uuid',
            field=models.CharField(default=uuid.UUID('e5e50462-8a6e-4d52-8404-1cc0be03cca2'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='lagesample',
            name='uuid',
            field=models.CharField(default=uuid.UUID('bcb1ca67-3f1c-45c2-a43d-a62635fb75e2'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='lamesample',
            name='uuid',
            field=models.CharField(default=uuid.UUID('dec57d4f-2d54-4a3e-b65a-3bc008a8d449'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customappmodel',
            name='datavarchar',
            field=models.CharField(default=uuid.UUID('311a63ce-5c1d-494b-8b5b-a2c9aa1b05dc'), max_length=255, primary_key=True, serialize=False),
        ),
    ]
