# Generated by Django 5.1 on 2024-09-04 13:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0006_samples_lab_id_alter_administration_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('45d4ace3-2dcc-4dec-abdd-3c34b7280917'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
