# Generated by Django 5.1 on 2024-09-09 14:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0007_alter_administration_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('3ddec859-ffff-40c9-aafb-15004529000c'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
