# Generated by Django 5.0.6 on 2024-07-17 11:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0007_labdmp_alter_administration_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='uuid',
            field=models.CharField(default=uuid.UUID('40a71fe4-28e2-4117-b84c-80ed9dc851fd'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customappmodel',
            name='datavarchar',
            field=models.CharField(default=uuid.UUID('1d5d80b7-d211-4195-8842-bed20fba37a5'), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='uuid',
            field=models.CharField(default=uuid.UUID('87d988d2-d13f-4a8d-92ae-f11b3a2212ed'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
