# Generated by Django 5.1 on 2024-09-04 13:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0007_alter_administration_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('7533a95d-4f69-4379-b1b1-d0977869374f'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='samples',
            name='sr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.servicerequests'),
        ),
    ]
