# Generated by Django 5.0.6 on 2024-07-17 14:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0008_alter_administration_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labdmp',
            name='additional_enotebook_open_collection',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labdmp',
            name='metadata_schema_defined',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labdmp',
            name='sample_standard',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administration',
            name='uuid',
            field=models.CharField(default=uuid.UUID('3e999c79-62e4-44d3-807c-dc81db2368b0'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customappmodel',
            name='datavarchar',
            field=models.CharField(default=uuid.UUID('a72ef041-c4dc-4b5e-bbdf-694fde787d18'), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='uuid',
            field=models.CharField(default=uuid.UUID('2f2378b7-f79a-4cee-9e0f-cfe54d479380'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
