# Generated by Django 5.0.6 on 2024-07-17 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0009_labdmp_additional_enotebook_open_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labdmp',
            name='additional_enotebook_open_collection',
        ),
        migrations.RemoveField(
            model_name='labdmp',
            name='metadata_schema_defined',
        ),
        migrations.RemoveField(
            model_name='labdmp',
            name='sample_standard',
        ),
        migrations.AlterField(
            model_name='administration',
            name='uuid',
            field=models.CharField(default=uuid.UUID('0e137333-1c4c-413f-8945-d7b73a3b45e3'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customappmodel',
            name='datavarchar',
            field=models.CharField(default=uuid.UUID('176f0b2e-d76d-4d77-80e9-4e6c097ada76'), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='uuid',
            field=models.CharField(default=uuid.UUID('cc02f4a3-a48f-4c67-b25e-aa843a17437a'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
