# Generated by Django 5.0.6 on 2024-07-17 15:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0010_remove_labdmp_additional_enotebook_open_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labdmp',
            name='additional_enotebook_open_collection',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labdmp',
            name='backup_policy_published_data',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labdmp',
            name='backup_policy_unplublished_data',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labdmp',
            name='clear_data_provenance',
            field=models.CharField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labdmp',
            name='instrument_metadata_collection',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labdmp',
            name='licence_scientific_documents',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labdmp',
            name='metadata_schema_defined',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labdmp',
            name='open_access_journal_publication',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labdmp',
            name='open_data_licence',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labdmp',
            name='open_trusted_repo_published_data',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labdmp',
            name='raw_data_storage_location',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labdmp',
            name='raw_data_storage_time_retention',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labdmp',
            name='related_data_open',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labdmp',
            name='sample_standard',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administration',
            name='uuid',
            field=models.CharField(default=uuid.UUID('d22548d6-71e0-49a1-946b-5821ecd022f9'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customappmodel',
            name='datavarchar',
            field=models.CharField(default=uuid.UUID('2b0bed7f-6494-4495-88ce-5f50ccbde46d'), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='uuid',
            field=models.CharField(default=uuid.UUID('cc55ab67-e125-4c24-962c-cfce2120f5cd'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
