# Generated by Django 5.0.6 on 2024-07-18 09:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0011_labdmp_additional_enotebook_open_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='uuid',
            field=models.CharField(default=uuid.UUID('8e0b1c12-16b1-4c49-9303-a7e38bfe537a'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customappmodel',
            name='datavarchar',
            field=models.CharField(default=uuid.UUID('6ab1e2aa-3a89-4d3f-9ee2-2f32a08085ee'), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='clear_data_provenance',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='open_access_journal_publication',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='open_trusted_repo_published_data',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='related_data_open',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='uuid',
            field=models.CharField(default=uuid.UUID('94c917bc-1e57-494e-bc69-eb037aa15b7f'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
