# Generated by Django 5.0.6 on 2024-07-18 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0012_alter_administration_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='uuid',
            field=models.CharField(default=uuid.UUID('03b0a8f8-5786-4a33-94d8-0e4425563af5'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customappmodel',
            name='datavarchar',
            field=models.CharField(default=uuid.UUID('6a6eaaf7-bbe3-4a96-9b64-b7690eb5d452'), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='licence_scientific_documents',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='uuid',
            field=models.CharField(default=uuid.UUID('22145659-3586-47c7-b92c-ec898eecb556'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
