# Generated by Django 5.0.6 on 2024-07-18 10:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0013_alter_administration_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='uuid',
            field=models.CharField(default=uuid.UUID('e9139b30-ecd8-4844-b587-022f4e54c383'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customappmodel',
            name='datavarchar',
            field=models.CharField(default=uuid.UUID('f00cab6b-f1cb-4bac-ba2b-20d510002277'), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='uuid',
            field=models.CharField(default=uuid.UUID('bbb64576-e6ed-436a-8123-02cf06f72e82'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
