# Generated by Django 5.0.6 on 2024-07-18 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0014_alter_administration_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='uuid',
            field=models.CharField(default=uuid.UUID('4b51f425-1959-482b-94f1-b02c387d3328'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customappmodel',
            name='datavarchar',
            field=models.CharField(default=uuid.UUID('f78d6e81-4143-4979-94d0-827935025133'), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='additional_enotebook_open_collection',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='backup_policy_published_data',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='backup_policy_unplublished_data',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='clear_data_provenance',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='instrument_metadata_collection',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='licence_scientific_documents',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='metadata_schema_defined',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='open_access_journal_publication',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='open_data_licence',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='open_trusted_repo_published_data',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='raw_data_storage_location',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='raw_data_storage_time_retention',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='related_data_open',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='sample_standard',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='uuid',
            field=models.CharField(default=uuid.UUID('7090fde2-d041-4cb5-ab57-ec7521a658e4'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
