# Generated by Django 5.0.6 on 2024-07-18 10:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0015_alter_administration_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labdmp',
            name='datageneric',
        ),
        migrations.AlterField(
            model_name='administration',
            name='uuid',
            field=models.CharField(default=uuid.UUID('d3d58800-f89f-4909-926f-22ec97913f5c'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customappmodel',
            name='datavarchar',
            field=models.CharField(default=uuid.UUID('a5051ea0-90cd-4878-ab07-c8049cf47b89'), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='uuid',
            field=models.CharField(default=uuid.UUID('eb373feb-5a21-4ce1-8b38-bec037bda1fa'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
