# Generated by Django 5.0.6 on 2024-07-18 12:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0016_remove_labdmp_datageneric_alter_administration_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='uuid',
            field=models.CharField(default=uuid.UUID('ff2e8260-1342-4948-b4ed-a78d7f4295c1'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customappmodel',
            name='datavarchar',
            field=models.CharField(default=uuid.UUID('c2fff636-baf7-407b-b846-46405c06246e'), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='additional_enotebook_open_collection',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='instrument_metadata_collection',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='labname',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='labdmp',
            name='sample_standard',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='uuid',
            field=models.CharField(default=uuid.UUID('0ca4c0f7-8e7d-4bea-89b5-82c751efb3f0'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
