# Generated by Django 5.0.6 on 2024-07-18 14:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0017_alter_administration_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='uuid',
            field=models.CharField(default=uuid.UUID('e52b1eb4-e24b-4a6b-819f-06c94579111c'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customappmodel',
            name='datavarchar',
            field=models.CharField(default=uuid.UUID('b30d365a-990c-4073-a1f9-5b960b8e960c'), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='uuid',
            field=models.CharField(default=uuid.UUID('e9063f97-7cd9-49f9-ad20-0be71d633c37'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
