# Generated by Django 5.0.6 on 2024-07-18 14:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0018_alter_administration_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='labname',
            field=models.CharField(default='LAGE', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administration',
            name='uuid',
            field=models.CharField(default=uuid.UUID('4c711181-f047-4a64-9519-a393972c3fdf'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customappmodel',
            name='datavarchar',
            field=models.CharField(default=uuid.UUID('76118a21-3aca-4100-a24d-c99c7ba1bacb'), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='uuid',
            field=models.CharField(default=uuid.UUID('27460db0-7fdb-45d6-9a59-d8768fcfb549'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
