# Generated by Django 5.0.6 on 2024-07-18 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0019_administration_labname_alter_administration_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='uuid',
            field=models.CharField(default=uuid.UUID('b1008be0-b25c-4b7d-8685-7d2e4601dfb2'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customappmodel',
            name='datavarchar',
            field=models.CharField(default=uuid.UUID('abcb2363-f4df-4364-ba7d-e021800abf54'), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='uuid',
            field=models.CharField(default=uuid.UUID('cfd12a75-99c6-4acf-b5bb-be640a206f23'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
