# Generated by Django 5.0.7 on 2024-07-31 12:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0022_instruments_instrumentxtechnique_laboratories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lagesample',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PRP_CDM_app.instruments'),
        ),
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('226ed328-b3f2-40ed-82cc-2e1b8d91f97c'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('7f1f220c-48aa-4faf-8cac-8146f24aa6f8'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
