# Generated by Django 5.0.7 on 2024-08-07 06:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0023_lagesample_instrument_alter_administration_sr_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('871aa59f-cfa8-45f7-b733-1e1311f0af23'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('315758ea-8623-42fe-8b0e-89388be836c8'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
