# Generated by Django 5.0.7 on 2024-08-06 14:18

import PRP_CDM_app.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0023_lagesample_instrument_alter_administration_sr_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lagesamples',
            name='sample_id',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='sr_id',
        ),
        migrations.RemoveField(
            model_name='servicerequests',
            name='sr_feasibility',
        ),
        migrations.RemoveField(
            model_name='servicerequests',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='steps',
            name='sr_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='users',
            name='legal_status',
        ),
        migrations.RemoveField(
            model_name='users',
            name='research_role',
        ),
        migrations.AddField(
            model_name='lagesamples',
            name='samples_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PRP_CDM_app.samples'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='sample_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.samples'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samples',
            name='sample_feasibility',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='samples',
            name='sample_tatus',
            field=models.CharField(default='Submitted’'),
        ),
        migrations.AddField(
            model_name='steps',
            name='sample_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.samples'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('c6d261c6-7c97-41c5-a038-07b92ab55122'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instrumentxtechnique',
            name='instrument_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.instruments'),
        ),
        migrations.AlterField(
            model_name='instrumentxtechnique',
            name='technique_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.techniques'),
        ),
        migrations.AlterField(
            model_name='labxinstrument',
            name='instrument_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.instruments'),
        ),
        migrations.AlterField(
            model_name='labxinstrument',
            name='lab_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.laboratories'),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('bae846c3-75d6-4fc6-9f5d-2fb1f990a460'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='samples',
            name='sr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.servicerequests'),
        ),
        migrations.AlterField(
            model_name='servicerequests',
            name='lab_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.laboratories'),
        ),
        migrations.AlterField(
            model_name='servicerequests',
            name='sr_status',
            field=models.CharField(default='Submitted’'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='instrument_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.instruments'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='technique_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.techniques'),
        ),
        migrations.CreateModel(
            name='Proposals',
            fields=[
                ('proposal_id', models.CharField(max_length=37, primary_key=True, serialize=False)),
                ('proposal_status', models.CharField(default='Submitted’')),
                ('proposal_feasibility', models.CharField(blank=True)),
                ('proposal_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.Proposals.user_directory_path)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.users')),
            ],
            options={
                'db_table': 'proposals',
            },
        ),
        migrations.AddField(
            model_name='servicerequests',
            name='proposal_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.proposals'),
            preserve_default=False,
        ),
    ]
