# Generated by Django 5.0.7 on 2024-08-06 14:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0024_remove_lagesamples_sample_id_remove_questions_sr_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('27474947-4890-4610-9e8e-3232937ef7bc'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('30652483-7eb9-4cef-bdb8-16361937785d'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
