# Generated by Django 5.0.7 on 2024-08-06 15:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0025_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('b89c553c-da91-453d-b4e1-e2c85352a3d0'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('359b01bd-c300-4473-9feb-3068caa10d1c'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
