# Generated by Django 5.0.7 on 2024-08-06 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0026_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='legal_status',
            field=models.CharField(choices=[('OTH', 'male'), ('PRV', 'female'), ('RES', 'other'), ('SME', 'other'), ('UNI', 'other')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='research_role',
            field=models.CharField(choices=[('senior scientist', 'senior scientist'), ('phd student', 'phd student'), ('professor / scientific coordinator', 'professor / scientific coordinator'), ('scientist', 'scientist'), ('manager', 'manager'), ('degree student', 'degree student'), ('post-doc', 'post-doc'), ('technician', 'technician'), ('other', 'other')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('b230cd9e-4909-47cd-8191-620bc9ab2d85'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('1e6414e7-da06-4cba-902f-fec4f7a91564'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
