# Generated by Django 5.0.7 on 2024-08-06 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0027_users_gender_users_legal_status_users_research_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('142c20a8-b19b-4596-b1ec-903ec600c043'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('0e6374e0-bb81-4b24-8f6b-c89d5863f6ee'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='legal_status',
            field=models.CharField(choices=[('OTH', 'OTH'), ('PRV', 'PRV'), ('RES', 'RES'), ('SME', 'SME'), ('UNI', 'UNI')]),
        ),
    ]
