# Generated by Django 5.0.7 on 2024-08-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0024_alter_administration_sr_id_alter_lagesample_sr_id'),
        ('PRP_CDM_app', '0028_alter_administration_sr_id_alter_lagesample_sr_id_and_more'),
    ]

    operations = [
    ]
