# Generated by Django 5.0.7 on 2024-08-07 07:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0029_merge_20240807_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('8b67f10d-6767-4c1d-b119-54d6f4d338ea'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('2ef91d5a-6ade-4040-b4dd-a9571e5922c5'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
