# Generated by Django 5.0.7 on 2024-08-07 12:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0030_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('4774f199-dee2-4688-969c-2913b7620353'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('709a9d36-2b28-4080-b1dd-5c3bdf1d5570'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
