# Generated by Django 5.0.7 on 2024-08-07 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0031_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('a3098d80-39ee-4894-a279-cd5e02e156cd'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('b1136110-c0cc-41dd-b747-bfdad43fbf85'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
