# Generated by Django 5.0.7 on 2024-08-07 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0032_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('164f3ca3-06b8-4890-b9dd-0f9773891e0b'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('3a5803b4-b3d9-4c54-b49e-d124e9cfcd3f'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
