# Generated by Django 5.0.7 on 2024-08-07 12:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0033_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('34a73392-d8c8-4e62-baa4-81b67fd47e45'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('fe51ac38-7628-4313-ad08-73fc7692b03f'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
