# Generated by Django 5.0.7 on 2024-08-26 07:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0034_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('42c3ccb2-7bbd-429c-b920-85cef29dd208'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('41a34449-07f9-459b-8b0a-5ade51f6977a'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
