# Generated by Django 5.1 on 2024-08-19 09:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0034_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('2d34784d-1ede-40f4-b38c-36e1c3778ffb'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('c0253315-099a-40e3-9d32-bb63735e6bed'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
