# Generated by Django 5.1 on 2024-08-19 09:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0036_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('443f4908-f5c7-4424-ae2d-feb8a86ba7a3'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('f0d54556-8d63-4730-9a8c-bf5a3c7269ac'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
