# Generated by Django 5.1 on 2024-08-19 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0038_alter_administration_sr_id_alter_lagesample_sr_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('2496946c-a05f-4aed-8905-7599df795558'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('89a68502-3127-49bb-a67c-147a386be351'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
