# Generated by Django 5.1 on 2024-08-19 12:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0039_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('b281354d-0a9c-4e79-8ff3-0fe2abf85580'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('645c7e56-95f7-408a-9047-2814ca4282ce'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
