# Generated by Django 5.1 on 2024-08-20 07:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0040_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('d633b275-3b38-4745-833e-9344466bfded'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('1cec7a97-dfab-4ff5-b3fc-20e33a58b537'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
