# Generated by Django 5.1 on 2024-08-20 07:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0041_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('be485195-e32b-416d-a2af-777fc94dea2d'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('12b8d998-dc3f-4679-9a65-2d347199cdce'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
