# Generated by Django 5.1 on 2024-08-20 08:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0042_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('9e4ab6d0-fcb6-4e13-a47f-c3df4f6a360c'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('275b5623-f787-4db1-8556-45f6482347b2'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
