# Generated by Django 5.1 on 2024-08-20 10:19

import PRP_CDM_app.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0043_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LameSamples',
            fields=[
                ('samples_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PRP_CDM_app.samples')),
                ('chemical_formula', models.CharField(blank=True)),
                ('elements_list', models.CharField(blank=True)),
                ('sample_date_of_delivery', models.DateField()),
                ('sample_back', models.BooleanField()),
                ('sample_sheet_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.LameSamples.user_directory_path)),
                ('additional_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.LameSamples.user_directory_path)),
            ],
            options={
                'db_table': 'lame_samples',
            },
            bases=('PRP_CDM_app.samples',),
        ),
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('466485fd-8be4-4175-b1d2-26f77f5209b0'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('807e6c90-7457-44f2-b58a-c4031a1d4dc6'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='proposal_status',
            field=models.CharField(default='Submitted'),
        ),
        migrations.AlterField(
            model_name='samples',
            name='sample_feasibility',
            field=models.CharField(blank=True, choices=[('feasible', 'feasible'), ('not feasible', 'not feasible'), ('feasible with reservations', 'feasible with reservations')]),
        ),
        migrations.AlterField(
            model_name='samples',
            name='sample_tatus',
            field=models.CharField(default='Submitted'),
        ),
        migrations.AlterField(
            model_name='samples',
            name='type',
            field=models.CharField(blank=True, choices=[('DNA', 'DNA'), ('RNA', 'RNA'), ('pellet', 'pellet'), ('biopsy', 'biopsy')]),
        ),
        migrations.AlterField(
            model_name='servicerequests',
            name='sr_status',
            field=models.CharField(default='Submitted'),
        ),
    ]
