# Generated by Django 5.1 on 2024-08-20 11:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0044_lamesamples_alter_administration_sr_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('9cf2392a-de61-40be-8b91-87b55237b2e4'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('1166dd02-5dbd-49a5-a550-c31e1e31532c'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
