# Generated by Django 5.1 on 2024-08-20 12:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0045_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('a3b1bd73-3bc4-4569-a019-34ec35383011'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('515356df-fac0-4489-b3fe-5bbe90768100'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
