# Generated by Django 5.1 on 2024-08-20 12:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0046_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('8b3e3f08-46bb-4435-a873-60673f0e6ada'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('a7a8348e-1644-415e-99e7-9892621b489e'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
