# Generated by Django 5.1 on 2024-08-20 12:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0047_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('8696e23a-245f-4fba-bc3b-ac93c967e602'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('9ca860bd-9b85-4907-b6e0-fbdd4595548d'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
