# Generated by Django 5.1 on 2024-08-20 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0048_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('499f7ce7-4425-4289-84a0-e9627862eff2'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('167ef059-af2b-4a4a-b270-b67309833a6e'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
