# Generated by Django 5.1 on 2024-08-20 13:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0049_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('006ed835-86ba-47e0-9626-aa019e81fd97'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('2a88332b-0d63-4707-85fe-6827bce3f5e3'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
