# Generated by Django 5.1 on 2024-08-20 13:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0050_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('f85cec8b-0033-4533-9310-3ee220d8f11c'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('50f70ca5-de92-4c78-aebf-442b8435cece'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
