# Generated by Django 5.1 on 2024-08-26 14:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0051_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('16698bd6-da18-40f9-9497-ced3e24764df'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('65d9667f-724e-4f4e-a81b-983bfee1ba29'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
