# Generated by Django 5.1 on 2024-08-26 14:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0052_alter_administration_sr_id_alter_lagesample_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('a8927db1-9516-4386-a60a-32e8bd92043c'), max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lagesample',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('7a6b4503-ada5-4e99-97f7-202c1f92d7b1'), max_length=37, primary_key=True, serialize=False),
        ),
    ]
