# Generated by Django 5.1.4 on 2025-01-17 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0002_administration_instruments_instrumentxtechnique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='sample_location',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samples',
            name='sample_short_description',
            field=models.CharField(default='empty short description', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='instrument_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instrumentxtechnique',
            name='x_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='laboratories',
            name='lab_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='labxinstrument',
            name='x_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='proposal_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='samples',
            name='sample_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicerequests',
            name='sr_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='steps',
            name='step_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='techniques',
            name='technique_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='legal_status',
            field=models.CharField(blank=True, choices=[('OTH', 'OTH'), ('PRV', 'PRV'), ('RES', 'RES'), ('SME', 'SME'), ('UNI', 'UNI')], null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='API_Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elab_token', models.CharField(blank=True, max_length=128, null=True)),
                ('jenkins_token', models.CharField(blank=True, max_length=128, null=True)),
                ('laboratory', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.laboratories')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.users')),
            ],
            options={
                'db_table': 'api_tokens',
            },
        ),
    ]
