# Generated by Django 5.1.3 on 2024-11-19 15:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0003_alter_administration_sr_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='elab_token',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('b9d42cfa-b805-47e2-83bb-acabf7996b21'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
