# Generated by Django 5.1.4 on 2025-01-08 08:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0004_users_elab_token_alter_administration_sr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='jenkins_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('983ba1c7-9001-4c6c-b4e3-a3150bd1eca0'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='elab_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='legal_status',
            field=models.CharField(blank=True, choices=[('OTH', 'OTH'), ('PRV', 'PRV'), ('RES', 'RES'), ('SME', 'SME'), ('UNI', 'UNI')], null=True),
        ),
    ]
