# Generated by Django 5.1.4 on 2025-01-08 10:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0005_users_jenkins_token_alter_administration_sr_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('c8438af1-5bd7-414e-9c61-1db298befbef'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
