# Generated by Django 5.1.4 on 2025-01-08 16:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0006_alter_administration_sr_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='elab_token',
        ),
        migrations.RemoveField(
            model_name='users',
            name='jenkins_token',
        ),
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('492aec47-6f4c-4160-8378-e00a10c67a78'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='API_Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elab_token', models.CharField(blank=True, max_length=128, null=True)),
                ('jenkins_token', models.CharField(blank=True, max_length=128, null=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.laboratories')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.users')),
            ],
        ),
    ]
