# Generated by Django 5.1.4 on 2025-01-08 16:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0007_remove_users_elab_token_remove_users_jenkins_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('a33665f9-9ede-4c7a-85b2-6f6cf01ba57a'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
