# Generated by Django 5.1.4 on 2025-01-08 16:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0008_alter_administration_sr_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api_tokens',
            old_name='username',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('b387172d-dfc5-43c1-a508-2aa7cb6be134'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
