# Generated by Django 5.1.4 on 2025-01-08 16:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0009_rename_username_api_tokens_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('a28ec12c-6525-4a88-9d55-84ac4f8ea046'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='api_tokens',
            table='api_tokens',
        ),
    ]
