# Generated by Django 5.1.4 on 2025-01-09 13:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0010_alter_administration_sr_id_alter_api_tokens_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='sample_short_description',
            field=models.TextField(default='No Title', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('204ba479-4d51-4fa3-af71-c7561effa20c'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='api_tokens',
            name='laboratory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.laboratories'),
        ),
    ]
