# Generated by Django 5.1.4 on 2025-01-13 10:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0011_samples_sample_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='sample_location',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('b4725c92-3191-4c12-a6d8-ac281cce433b'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='samples',
            name='sample_short_description',
            field=models.CharField(max_length=64),
        ),
    ]
