# Generated by Django 5.1.4 on 2025-01-14 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0012_samples_sample_location_alter_administration_sr_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('304b8986-b4c5-4aa5-a99c-1a50a1faede5'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
