# Generated by Django 5.1.4 on 2025-01-15 09:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0013_alter_administration_sr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='sr_id',
            field=models.CharField(default=uuid.UUID('6ccf3a11-1fdc-4605-99fe-96d69c1367e6'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
