# Generated by Django 5.0.6 on 2024-06-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datavarchar', models.CharField(max_length=255)),
                ('dataint', models.IntegerField()),
            ],
            options={
                'db_table': 'customappmodel',
            },
        ),
    ]
