# Generated by Django 5.0.6 on 2024-06-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_db_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customappmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='customappmodel',
            name='datausername',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customappmodel',
            name='datavarchar',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
